---
language: objective-c
osx_image: xcode7.2

script:
  - echo I Objective-C what you did there.
  - uname -a
  - sw_vers -productVersion
  - motion --version
  - pod --version
  - xcpretty --version
  - xctool -version
  - fastlane --version
  - carthage version
  - gem install faraday
  - ruby test_ssl.rb
#  - rvm reinstall 2.0.0-p643 --disable-binary
#  - ruby test_ssl.rb
